name: Healer
version: 1.0
main: me.jackears.Healer
author: JACKEARS
description: Healer!
commands:
  heal:
    usage: /<command> {player}
    description: Let's you heal players!
    aliases: [healer, health, boost]